# Generated by Django 4.2.5 on 2023-11-15 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=80)),
                ("synopsis", models.TextField()),
                ("genre", models.CharField(max_length=80)),
                ("release_date", models.DateField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("available", "Disponível"),
                            ("unavailable", "Indisponível"),
                            ("soon", "Em Breve"),
                        ],
                        max_length=12,
                    ),
                ),
                ("stock", models.IntegerField()),
                ("loan_count", models.IntegerField(default=0)),
                (
                    "front_cover",
                    models.ImageField(
                        blank=True, null=True, upload_to="static/images/"
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("final_date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="UserLoan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("is_on", models.BooleanField(default=False)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan",
                        to="website.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
