# Generated by Django 4.2.5 on 2023-11-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historyuserloan",
            name="was_on",
            field=models.BooleanField(default=False),
        ),
    ]
