# Generated by Django 4.2.5 on 2023-11-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="stock",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
