# Generated by Django 4.2.5 on 2023-11-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_remove_book_final_date_remove_book_start_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userloan",
            name="date",
        ),
        migrations.AlterField(
            model_name="userloan",
            name="final_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="userloan",
            name="start_date",
            field=models.DateField(),
        ),
    ]
