# Generated by Django 4.2.5 on 2023-09-19 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_members_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
    ]
