# Generated by Django 4.2.5 on 2023-10-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0002_delete_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=80)),
                ('synopsis', models.TextField()),
                ('release_date', models.DateField()),
                ('is_available', models.BooleanField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images/')),
            ],
        ),
    ]
