# Generated by Django 4.2.5 on 2023-11-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_book_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="userloan",
            name="is_on",
            field=models.BooleanField(default=False),
        ),
    ]
