# Generated by Django 4.2.5 on 2023-11-18 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0003_remove_userloan_date_alter_userloan_final_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('antiques & collectibles', 'Antiguidades & Colecionáveis'), ('literary collections', 'Coleções Literárias'), ('architecture', 'Arquitetura'), ('literary criticism', 'Crítica Literária'), ('art', 'Arte'), ('mathematics', 'Matemática'), ('bibles', 'Bíblias'), ('medical', 'Médico'), ('biography & autobiography', 'Biografias & Autobiografias'), ('music', 'Música'), ('body, mind & spirit', 'Corpo, Mente & Espírito'), ('nature', 'Natureza'), ('business & economics', 'Negócios & Economia'), ('performing arts', 'Artes Performáticas'), ('comics & graphic novels', 'Quadrinhos & Romances Gráficos'), ('pets', 'Animais de Estimação'), ('computers', 'Computadores'), ('philosophy', 'Filosofia'), ('cooking', 'Culinária'), ('photography', 'Fotografia'), ('crafts & hobbies', 'Artesanato & Hobbies'), ('poetry', 'Poesia'), ('design', 'Design'), ('political science', 'Ciência Política'), ('drama', 'Drama'), ('psychology', 'Psicologia'), ('education', 'Educação'), ('reference', 'Referência'), ('family & relationships', 'Família & Relacionamentos'), ('religion', 'Religião'), ('fiction', 'Ficção'), ('science', 'Ciência'), ('foreign language study', 'Estudo de Idiomas'), ('self-help', 'Autoajuda'), ('games & activities', 'Jogos & Atividades'), ('social science', 'Ciência Social'), ('gardening', 'Jardinagem'), ('sports & recreation', 'Esportes & Lazer'), ('health & fitness', 'Saúde & Fitness'), ('study aids', 'Apoios de Estudo'), ('history', 'História'), ('technology & engineering', 'Tecnologia & Engenharia'), ('house & home', 'Casa & Lar'), ('transportation', 'Transporte'), ('humor', 'Humor'), ('travel', 'Viagem'), ('juvenile fiction', 'Ficção Juvenil'), ('true crime', 'Crime Verdadeiro'), ('juvenile nonfiction', 'Não Ficção Juvenil'), ('young adult fiction', 'Ficção para Jovens Adultos'), ('language arts & disciplines', 'Artes da Linguagem & Disciplinas'), ('young adult nonfiction', 'Não Ficção para Jovens Adultos'), ('law', 'Direito')], max_length=255),
        ),
        migrations.CreateModel(
            name='HistoryUserLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_on', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('final_date', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_loan', to='website.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
