# Generated by Django 4.2.5 on 2023-11-10 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_userloan_is_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userloan",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loan",
                to="website.book",
            ),
        ),
    ]
