# Generated by Django 4.2.5 on 2023-10-01 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='image',
            new_name='front_cover',
        ),
    ]
