# Generated by Django 4.2.5 on 2023-11-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_alter_userloan_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="loan_count",
            field=models.IntegerField(default=0),
        ),
    ]
