# Generated by Django 4.2.5 on 2023-11-18 19:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_book_genre_historyuserloan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='state',
            new_name='status',
        ),
        migrations.AddField(
            model_name='book',
            name='added_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='origin',
            field=models.CharField(choices=[('bought', 'Comprado'), ('donated', 'Doado'), ('unknown', 'Não especificado')], default='not specified', max_length=12),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
