# Generated by Django 4.2.5 on 2023-11-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_state_book_status_book_added_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='origin',
            field=models.CharField(choices=[('available', 'Disponível'), ('unavailable', 'Indisponível'), ('soon', 'Em Breve')], default='unknown', max_length=12),
        ),
    ]
