# Generated by Django 4.2.5 on 2023-11-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_book_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='origin',
            field=models.CharField(choices=[('bought', 'Comprado'), ('donated', 'Doado'), ('unknown', 'Não especificado')], default='unknown', max_length=12),
        ),
    ]
