# Generated by Django 4.2.5 on 2023-11-18 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_book_origin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='comments',
            new_name='comment',
        ),
    ]
