# Generated by Django 4.2.5 on 2023-11-20 16:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0009_userwishlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historyuserloan",
            name="is_on",
        ),
    ]
