# Generated by Django 4.2.5 on 2023-11-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0010_remove_historyuserloan_is_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="userloan",
            name="renews",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
