# Generated by Django 4.2.5 on 2023-11-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0011_userloan_renews"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userloan",
            name="renews",
            field=models.IntegerField(default=1),
        ),
    ]
