# Generated by Django 4.2.5 on 2023-11-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0012_alter_userloan_renews"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="front_cover",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/images/front_covers/"
            ),
        ),
    ]
