# Generated by Django 4.2.5 on 2023-11-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "Um usuário com este e-mail já existe."},
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                error_messages={"unique": "Um usuário com este nome já existe."},
                max_length=255,
                unique=True,
            ),
        ),
    ]
