# Generated by Django 4.2.5 on 2023-09-29 17:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0002_member_is_valid"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Member",
        ),
    ]
