# Generated by Django 4.2.5 on 2023-11-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0002_user_is_librarian"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="static/images/"),
        ),
    ]
