# Generated by Django 4.2.5 on 2023-11-04 17:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0002_alter_user_email_alter_user_full_name"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
