# Generated by Django 4.2.5 on 2023-11-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0005_alter_user_course_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="course",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
